#!/bin/bash

NAME=jayakrishna
COMPANY=DeutscheBank
ROLE=Associate
EXPERIENCE=5years
TECHNOLOGY_LEARNING=devops_AWS
MARRIED=harini
MARRIAGE_DATE=16thnov2024
PLACE=Guntur
SALARY=good

echo $NAME
echo $COMPANY
echo $ROLE
echo $TECHNOLOGY_LEARNING
echo $MARRIED
echo $EXPERIENCE
echo $MARRIAGE_DATE
echo $PLACE
echo $SALARY